import {
  BookOpenIcon,
  BotIcon,
  CalendarIcon,
  CheckSquareIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  DatabaseIcon,
  DollarSignIcon,
  DropletIcon,
  EditIcon,
  FileJsonIcon,
  FileTextIcon,
  FilmIcon,
  GlobeIcon,
  HomeIcon,
  ImageIcon,
  LayoutIcon,
  ListTodoIcon,
  MessageSquareIcon,
  Music2Icon,
  MusicIcon,
  NewspaperIcon,
  ScrollIcon,
  SearchIcon,
  SparklesIcon,
  TargetIcon,
  TreePineIcon,
  TrelloIcon,
  TrendingUpIcon,
  UsersIcon,
  WavesIcon,
  YoutubeIcon,
  ZapIcon,
} from "lucide-react";

export const mimic: Mimic = {
  modules: [
    { name: "Home", icon: HomeIcon, path: "/" },
    {
      name: "To-Do List",
      icon: ListTodoIcon,
      path: "/todo",
      category: "productivity",
    },
    {
      name: "Kanban",
      icon: TrelloIcon,
      path: "/kanban",
      category: "productivity",
    },
    {
      name: "Pomodoro",
      icon: ClockIcon,
      path: "/pomodoro",
      category: "productivity",
    },
    {
      name: "Notepad",
      icon: ScrollIcon,
      path: "/notepad",
      category: "productivity",
    },
    {
      name: "Water Reminder",
      icon: DropletIcon,
      path: "/water-reminder",
      category: "productivity",
    },
    {
      name: "Internet Search",
      icon: GlobeIcon,
      path: "/internet-search",
      category: "productivity",
    },
    {
      name: "Lo-Fi Music",
      icon: MusicIcon,
      path: "/lofi",
      category: "entertainment",
    },
    {
      name: "YouTube Player",
      icon: YoutubeIcon,
      path: "/youtube-player",
      category: "entertainment",
    },
    {
      name: "Currency Converter",
      icon: DollarSignIcon,
      path: "/currency-converter",
      category: "utilities",
    },
    {
      name: "Tech News",
      icon: NewspaperIcon,
      path: "/tech-news",
      category: "utilities",
    },
    {
      name: "AI Tools",
      icon: BotIcon,
      path: "/ai-tools",
      category: "development",
    },
    {
      name: "Deploy Checklist",
      icon: CheckSquareIcon,
      path: "/deploy-checklist",
      category: "development",
    },
    {
      name: "Code Snippets",
      icon: FileTextIcon,
      path: "/code-snippets",
      category: "development",
    },
    {
      name: "Quick Search",
      icon: SearchIcon,
      path: "/search",
      category: "development",
    },
    {
      name: "Fake Data",
      icon: DatabaseIcon,
      path: "/fake-data",
      category: "development",
    },
    {
      name: "JSON Formatter",
      icon: FileJsonIcon,
      path: "/json-formatter",
      category: "development",
    },
    { name: "Apoie o Projeto", icon: CoffeeIcon, path: "/donation" },
  ],
  liveStreams: [
    {
      id: "chillhop",
      name: "Chillhop Radio",
      url: "https://streams.fluxfm.de/Chillhop/mp3-320/streams.fluxfm.de/",
      description: "Lo-fi hip hop beats to relax/study to",
    },
    {
      id: "lofi-girl",
      name: "Lo-Fi Cafe",
      url: "https://streams.fluxfm.de/Lounge/mp3-320/streams.fluxfm.de/",
      description: "Peaceful coffee shop ambience",
    },
    {
      id: "study-beats",
      name: "Study Beats",
      url: "https://streams.fluxfm.de/Chillout/mp3-320/streams.fluxfm.de/",
      description: "Perfect for concentration and focus",
    },
    {
      id: "ambient-sounds",
      name: "Ambient Sounds",
      url: "https://streams.fluxfm.de/Ambient/mp3-320/streams.fluxfm.de/",
      description: "Relaxing ambient soundscapes",
    },
    {
      id: "nature-sounds",
      name: "Nature Sounds",
      url: "https://streams.fluxfm.de/Nature/mp3-320/streams.fluxfm.de/",
      description: "Soothing nature sounds for relaxation",
    },
  ],
  sounds: [
    {
      id: "rain",
      name: "Rain",
      icon: CloudIcon,
      color: "text-blue-500",
      url: "https://www.soundjay.com/misc/sounds/rain-01.wav",
    },
    {
      id: "beats",
      name: "Lo-Fi Beats",
      icon: Music2Icon,
      color: "text-purple-500",
      url: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    },
    {
      id: "ocean",
      name: "Ocean Waves",
      icon: WavesIcon,
      color: "text-cyan-500",
      url: "https://www.soundjay.com/misc/sounds/water-01.wav",
    },
    {
      id: "cafe",
      name: "Coffee Shop",
      icon: CoffeeIcon,
      color: "text-amber-500",
      url: "https://www.soundjay.com/misc/sounds/coffee-shop-01.wav",
    },
    {
      id: "forest",
      name: "Forest",
      icon: TreePineIcon,
      color: "text-green-500",
      url: "https://www.soundjay.com/misc/sounds/forest-01.wav",
    },
  ],
  lofiStations: [
    {
      name: "ChilledCow Radio",
      url: "https://www.youtube.com/embed/jfKfPfyJRdk?autoplay=1&controls=0&loop=1",
      description: "24/7 lofi hip hop radio",
    },
    {
      name: "Lofi Girl Study",
      url: "https://www.youtube.com/embed/4xDzrJKXOOY?autoplay=1&controls=0&loop=1",
      description: "Perfect for studying",
    },
    {
      name: "Jazz Lofi",
      url: "https://www.youtube.com/embed/Dx5qFachd3A?autoplay=1&controls=0&loop=1",
      description: "Jazzy lofi beats",
    },
  ],
  weather: {
    0: "Céu limpo",
    1: "Predominantemente limpo",
    2: "Parcialmente nublado",
    3: "Nublado",
    45: "Neblina",
    48: "Neblina com geada",
    51: "Garoa leve",
    53: "Garoa moderada",
    55: "Garoa intensa",
    61: "Chuva leve",
    63: "Chuva moderada",
    65: "Chuva intensa",
    71: "Neve leve",
    73: "Neve moderada",
    75: "Neve intensa",
    80: "Chuva leve",
    81: "Chuva moderada",
    82: "Chuva violenta",
    95: "Tempestade",
    96: "Tempestade com granizo",
    99: "Tempestade com granizo pesado",
  },
  pages: {
    aiTools: {
      tools: [
        {
          id: "chatgpt",
          name: "ChatGPT",
          description:
            "Assistente de IA conversacional avançado capaz de responder perguntas, auxiliar na escrita, explicar conceitos e muito mais.",
          url: "https://chat.openai.com/",
          image:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png",
          category: ["Chatbots", "Escrita", "Produtividade"],
          tags: ["IA Conversacional", "GPT", "OpenAI"],
          pricing: "Freemium",
          rating: 4.8,
          featured: true,
        },
        {
          id: "lovable",
          name: "Lovable",
          description:
            "Plataforma que permite criar aplicativos web completos conversando com uma IA. Ideal para prototipar e desenvolver projetos rapidamente.",
          url: "https://lovable.dev",
          image: "https://cdn.lovable.dev/assets/lovable-icon.png",
          category: ["Desenvolvimento", "Design"],
          tags: ["Desenvolvimento Web", "No-Code", "Low-Code"],
          pricing: "Freemium",
          rating: 4.7,
          featured: true,
        },
        {
          id: "midjourney",
          name: "Midjourney",
          description:
            "Ferramenta de geração de imagens por IA que cria ilustrações de alta qualidade a partir de descrições textuais.",
          url: "https://www.midjourney.com/",
          image:
            "https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png",
          category: ["Imagens", "Design"],
          tags: ["Geração de Imagens", "Arte Digital"],
          pricing: "Paid",
          rating: 4.9,
          featured: true,
        },
        {
          id: "copilot",
          name: "GitHub Copilot",
          description:
            "Assistente de programação baseado em IA que ajuda a escrever código sugerindo linhas ou funções completas direto no seu editor.",
          url: "https://github.com/features/copilot",
          image:
            "https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.143.0/1700156764630/Microsoft.VisualStudio.Services.Icons.Default",
          category: ["Desenvolvimento", "Produtividade"],
          tags: ["Assistente de Código", "GitHub", "Programação"],
          pricing: "Paid",
          rating: 4.8,
        },
        {
          id: "perplexity",
          name: "Perplexity AI",
          description:
            "Mecanismo de pesquisa impulsionado por IA que fornece respostas detalhadas com citações de fontes, ideal para pesquisas aprofundadas.",
          url: "https://www.perplexity.ai/",
          image:
            "https://cdn.sanity.io/images/u0v1th4q/production/67045586fd9115ccb804bc7d6bee5ad2acf885c3-512x512.png",
          category: ["Pesquisa", "Conhecimento"],
          tags: ["Mecanismo de Busca", "Pesquisa IA"],
          pricing: "Freemium",
          rating: 4.6,
        },
        {
          id: "claude",
          name: "Claude AI",
          description:
            "Assistente de IA da Anthropic que se destaca por respostas detalhadas, nuancadas e por seguir instruções complexas.",
          url: "https://claude.ai/",
          image:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Logo_of_Claude_%28AI%29.svg/2048px-Logo_of_Claude_%28AI%29.svg.png",
          category: ["Chatbots", "Escrita", "Produtividade"],
          tags: ["IA Conversacional", "Anthropic"],
          pricing: "Freemium",
          rating: 4.7,
        },
        {
          id: "v0",
          name: "v0.dev",
          description:
            "Ferramenta de geração de interfaces por IA que cria código React e Tailwind a partir de descrições textuais.",
          url: "https://v0.dev/",
          image: "https://v0.dev/apple-icon.png",
          category: ["Desenvolvimento", "Design"],
          tags: ["UI/UX", "React", "Tailwind"],
          pricing: "Free",
          rating: 4.5,
        },
        {
          id: "dalle",
          name: "DALL-E",
          description:
            "Sistema de geração de imagens da OpenAI que cria imagens realistas e artísticas a partir de descrições textuais.",
          url: "https://openai.com/dall-e-3",
          image:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/DALL-E_Logo.png/800px-DALL-E_Logo.png",
          category: ["Imagens", "Design"],
          tags: ["Geração de Imagens", "OpenAI"],
          pricing: "Paid",
          rating: 4.8,
        },
        {
          id: "huggingface",
          name: "Hugging Face",
          description:
            "Plataforma que oferece acesso a milhares de modelos de IA de código aberto para várias tarefas como NLP, visão computacional e mais.",
          url: "https://huggingface.co/",
          image: "https://avatars.githubusercontent.com/u/25720743?s=200&v=4",
          category: ["Desenvolvimento", "Pesquisa"],
          tags: ["Modelos de IA", "Open-Source", "NLP"],
          pricing: "Freemium",
          rating: 4.6,
        },
        {
          id: "zapier",
          name: "Zapier AI",
          description:
            "Automatize tarefas com IA integrando centenas de aplicativos e criando fluxos de trabalho personalizados.",
          url: "https://zapier.com/ai",
          image:
            "https://cdn.sanity.io/images/ornj730p/production/e98e7e338de006d698f1094ebcac8a598f9d92bc-512x512.png",
          category: ["Automação", "Produtividade"],
          tags: ["Automação", "Integração"],
          pricing: "Freemium",
          rating: 4.5,
        },
        {
          id: "codeium",
          name: "Codeium",
          description:
            "Alternativa gratuita ao GitHub Copilot, oferece autocompletar de código em vários editores e linguagens de programação.",
          url: "https://codeium.com/",
          image: "https://codeium.com/favicon.ico",
          category: ["Desenvolvimento"],
          tags: ["Assistente de Código", "IA para Programação"],
          pricing: "Free",
          rating: 4.4,
        },
        {
          id: "elevenlabs",
          name: "ElevenLabs",
          description:
            "Plataforma de síntese de voz com IA que gera vozes humanas realistas em vários idiomas e estilos emocionais.",
          url: "https://elevenlabs.io/",
          image: "https://avatars.githubusercontent.com/u/121858069?s=200&v=4",
          category: ["Áudio", "Conteúdo"],
          tags: ["Síntese de Voz", "Text-to-Speech"],
          pricing: "Freemium",
          rating: 4.7,
        },
      ],
      categories: [
        { id: "all", name: "Todos", icon: SparklesIcon },
        { id: "chatbots", name: "Chatbots", icon: MessageSquareIcon },
        { id: "development", name: "Desenvolvimento", icon: CodeIcon },
        { id: "images", name: "Imagens", icon: ImageIcon },
        { id: "productivity", name: "Produtividade", icon: UsersIcon },
        { id: "research", name: "Pesquisa", icon: BookOpenIcon },
        { id: "audio", name: "Áudio", icon: MusicIcon },
        { id: "video", name: "Vídeo", icon: FilmIcon },
      ],
      categoryMap: {
        all: "Todos",
        chatbots: "Chatbots",
        development: "Desenvolvimento",
        images: "Imagens",
        productivity: "Produtividade",
        research: "Pesquisa",
        audio: "Áudio",
        video: "Vídeo",
        favorites: "Favoritos",
      },
    },
    codeSnippets: {
      languagesOptions: [
        { value: "javascript", label: "JavaScript" },
        { value: "typescript", label: "TypeScript" },
        { value: "python", label: "Python" },
        { value: "css", label: "CSS" },
        { value: "markup", label: "HTML" },
        { value: "php", label: "PHP" },
        { value: "java", label: "JAVA" },
        { value: "c", label: "C" },
        { value: "go", label: "GO" },
      ],
    },
    currencyConverter: {
      currencies: [
        { code: "USD", name: "Dólar Americano", symbol: "$", flag: "🇺🇸" },
        { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺" },
        { code: "BRL", name: "Real Brasileiro", symbol: "R$", flag: "🇧🇷" },
        { code: "GBP", name: "Libra Esterlina", symbol: "£", flag: "🇬🇧" },
        { code: "JPY", name: "Iene Japonês", symbol: "¥", flag: "🇯🇵" },
        { code: "CNY", name: "Yuan Chinês", symbol: "¥", flag: "🇨🇳" },
        { code: "AUD", name: "Dólar Australiano", symbol: "A$", flag: "🇦🇺" },
        { code: "CAD", name: "Dólar Canadense", symbol: "C$", flag: "🇨🇦" },
        { code: "CHF", name: "Franco Suíço", symbol: "CHF", flag: "🇨🇭" },
        { code: "ARS", name: "Peso Argentino", symbol: "$", flag: "🇦🇷" },
        { code: "MXN", name: "Peso Mexicano", symbol: "$", flag: "🇲🇽" },
        { code: "INR", name: "Rupia Indiana", symbol: "₹", flag: "🇮🇳" },
        { code: "KRW", name: "Won Sul-Coreano", symbol: "₩", flag: "🇰🇷" },
        { code: "SGD", name: "Dólar de Singapura", symbol: "S$", flag: "🇸🇬" },
        { code: "NOK", name: "Coroa Norueguesa", symbol: "kr", flag: "🇳🇴" },
        { code: "SEK", name: "Coroa Sueca", symbol: "kr", flag: "🇸🇪" },
        { code: "DKK", name: "Coroa Dinamarquesa", symbol: "kr", flag: "🇩🇰" },
        { code: "PLN", name: "Zloty Polonês", symbol: "zł", flag: "🇵🇱" },
        { code: "CZK", name: "Coroa Tcheca", symbol: "Kč", flag: "🇨🇿" },
        { code: "HUF", name: "Forint Húngaro", symbol: "Ft", flag: "🇭🇺" },
      ],
      sampleRates: {
        USD: {
          EUR: 0.92,
          BRL: 5.05,
          GBP: 0.78,
          JPY: 150.42,
          CNY: 7.23,
          AUD: 1.51,
          CAD: 1.35,
          CHF: 0.89,
          ARS: 875.22,
          MXN: 17.23,
          INR: 83.12,
          KRW: 1312.45,
          SGD: 1.34,
          NOK: 10.87,
          SEK: 10.45,
          DKK: 6.87,
          PLN: 4.12,
          CZK: 23.45,
          HUF: 356.78,
        },
        EUR: {
          USD: 1.09,
          BRL: 5.5,
          GBP: 0.85,
          JPY: 163.7,
          CNY: 7.87,
          AUD: 1.65,
          CAD: 1.47,
          CHF: 0.97,
          ARS: 952.89,
          MXN: 18.76,
          INR: 90.45,
          KRW: 1429.87,
          SGD: 1.46,
          NOK: 11.84,
          SEK: 11.38,
          DKK: 7.48,
          PLN: 4.49,
          CZK: 25.56,
          HUF: 388.92,
        },
        BRL: {
          USD: 0.2,
          EUR: 0.18,
          GBP: 0.15,
          JPY: 29.75,
          CNY: 1.43,
          AUD: 0.3,
          CAD: 0.27,
          CHF: 0.18,
          ARS: 173.33,
          MXN: 3.41,
          INR: 16.45,
          KRW: 259.78,
          SGD: 0.27,
          NOK: 2.15,
          SEK: 2.07,
          DKK: 1.36,
          PLN: 0.82,
          CZK: 4.64,
          HUF: 70.67,
        },
        GBP: {
          USD: 1.28,
          EUR: 1.18,
          BRL: 6.47,
          JPY: 192.65,
          CNY: 9.26,
          AUD: 1.93,
          CAD: 1.73,
          CHF: 1.14,
          ARS: 1120.79,
          MXN: 22.05,
          INR: 106.42,
          KRW: 1680.34,
          SGD: 1.72,
          NOK: 13.92,
          SEK: 13.38,
          DKK: 8.8,
          PLN: 5.28,
          CZK: 30.05,
          HUF: 457.23,
        },
      },
    },
    deployChecklist: {
      defaultItems: [
        { id: "1", text: "Executar todos os testes", completed: false },
        { id: "2", text: "Verificar mensagens de console", completed: false },
        {
          id: "3",
          text: "Verificar compatibilidade cross-browser",
          completed: false,
        },
        { id: "4", text: "Verificar responsividade", completed: false },
        { id: "5", text: "Otimizar imagens e assets", completed: false },
        { id: "6", text: "Verificar SEO", completed: false },
        { id: "7", text: "Validar formulários", completed: false },
        { id: "8", text: "Verificar performance", completed: false },
      ],
    },
    donation: {
      features: [
        {
          title: "Desenvolvimento Contínuo",
          description:
            "Ajude a manter o projeto atualizado com novos recursos e melhorias.",
        },
        {
          title: "Manutenção",
          description:
            "Apoie a correção de bugs e manutenção contínua do projeto.",
        },
        {
          title: "Novas Funcionalidades",
          description:
            "Contribua para o desenvolvimento de novas ferramentas e recursos.",
        },
        {
          title: "Café",
          description:
            "Às vezes, tudo o que precisamos é de mais uma xícara de café para continuar codificando! ☕",
        },
      ],
    },
    fakerData: {
      dataOptions: [
        { value: "name", label: "Nome", icon: "👤" },
        { value: "email", label: "Email", icon: "📧" },
        { value: "phone", label: "Telefone", icon: "📱" },
        { value: "address", label: "Endereço", icon: "🏠" },
        { value: "company", label: "Empresa", icon: "🏢" },
        { value: "job", label: "Profissão", icon: "💼" },
        { value: "creditCard", label: "Cartão de Crédito", icon: "💳" },
        { value: "product", label: "Produto", icon: "📦" },
        { value: "image", label: "URL de Imagem", icon: "🖼️" },
        { value: "uuid", label: "UUID", icon: "🔑" },
        { value: "date", label: "Data", icon: "📅" },
      ],
    },
    welcome: {
      categories: [
        {
          id: "productivity",
          name: "Produtividade",
          icon: <ZapIcon className="h-5 w-5" />,
          description: "Ferramentas para maximizar sua eficiência",
          color: "from-blue-500 to-cyan-500",
        },
        {
          id: "development",
          name: "Desenvolvimento",
          icon: <LayoutIcon className="h-5 w-5" />,
          description: "Utilitários essenciais para desenvolvedores",
          color: "from-purple-500 to-pink-500",
        },
        {
          id: "utilities",
          name: "Utilitários",
          icon: <GlobeIcon className="h-5 w-5" />,
          description: "Ferramentas práticas para o dia a dia",
          color: "from-green-500 to-emerald-500",
        },
        {
          id: "entertainment",
          name: "Entretenimento",
          icon: <MusicIcon className="h-5 w-5" />,
          description: "Relaxe e divirta-se durante os intervalos",
          color: "from-orange-500 to-red-500",
        },
      ],
      tools: [
        {
          name: "To-Do List",
          description: "Organize suas tarefas com facilidade",
          icon: <ListTodoIcon className="h-8 w-8" />,
          path: "/todo",
          category: "productivity",
          highlight: true,
        },
        {
          name: "Kanban Board",
          description: "Gerencie projetos com quadros visuais",
          icon: <TrelloIcon className="h-8 w-8" />,
          path: "/kanban",
          category: "productivity",
        },
        {
          name: "Pomodoro Timer",
          description: "Técnica de produtividade com intervalos",
          icon: <ClockIcon className="h-8 w-8" />,
          path: "/pomodoro",
          category: "productivity",
        },
        {
          name: "Notepad",
          description: "Anotações rápidas e simples",
          icon: <ScrollIcon className="h-8 w-8" />,
          path: "/notepad",
          category: "productivity",
        },
        {
          name: "Water Reminder",
          description: "Lembrete para se hidratar regularmente",
          icon: <DropletIcon className="h-8 w-8" />,
          path: "/water-reminder",
          category: "productivity",
        },
        {
          name: "Internet Search",
          description: "Pesquise na web entre as melhores opções do FlowHub",
          icon: <SearchIcon className="h-8 w-8" />,
          path: "/internet-search",
          category: "productivity",
        },
        {
          name: "AI Tools",
          description: "Ferramentas de inteligência artificial",
          icon: <BotIcon className="h-8 w-8" />,
          path: "/ai-tools",
          category: "development",
        },
        {
          name: "Deploy Checklist",
          description: "Lista de verificação para deploys",
          icon: <CheckSquareIcon className="h-8 w-8" />,
          path: "/deploy-checklist",
          category: "development",
        },
        {
          name: "Code Snippets",
          description: "Gerenciador de trechos de código",
          icon: <FileTextIcon className="h-8 w-8" />,
          path: "/code-snippets",
          category: "development",
        },
        {
          name: "Quick Search",
          description: "Pesquisa rápida em projetos",
          icon: <SearchIcon className="h-8 w-8" />,
          path: "/search",
          category: "development",
        },
        {
          name: "Fake Data Generator",
          description: "Gere dados falsos para testes",
          icon: <DatabaseIcon className="h-8 w-8" />,
          path: "/fake-data",
          category: "development",
        },
        {
          name: "JSON Formatter",
          description: "Formate e valide JSON facilmente",
          icon: <FileJsonIcon className="h-8 w-8" />,
          path: "/json-formatter",
          category: "development",
        },
        {
          name: "Currency Converter",
          description: "Conversor de moedas em tempo real",
          icon: <DollarSignIcon className="h-8 w-8" />,
          path: "/currency-converter",
          category: "utilities",
        },
        {
          name: "Tech News",
          description: "Últimas notícias de tecnologia",
          icon: <NewspaperIcon className="h-8 w-8" />,
          path: "/tech-news",
          category: "utilities",
        },
        {
          name: "Lo-Fi Music",
          description: "Concentre-se com música ambiente",
          icon: <MusicIcon className="h-8 w-8" />,
          path: "/lofi",
          category: "entertainment",
        },
        {
          name: "YouTube Player",
          description: "Player de vídeos do YouTube",
          icon: <YoutubeIcon className="h-8 w-8" />,
          path: "/youtube-player",
          category: "entertainment",
          highlight: true,
        },
      ],
    },
    kanban: {
      columnsConfig: [
        {
          id: "todo",
          title: "A Fazer",
          color: "text-blue-600",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
          icon: CalendarIcon,
        },
        {
          id: "inProgress",
          title: "Em Progresso",
          color: "text-yellow-600",
          bgColor: "bg-yellow-50 dark:bg-yellow-950/20",
          icon: ClockIcon,
        },
        {
          id: "review",
          title: "Em Revisão",
          color: "text-orange-600",
          bgColor: "bg-orange-50 dark:bg-orange-950/20",
          icon: EditIcon,
        },
        {
          id: "done",
          title: "Concluído",
          color: "text-green-600",
          bgColor: "bg-green-50 dark:bg-green-950/20",
          icon: TargetIcon,
        },
      ],
      priorityConfig: {
        low: {
          label: "Baixa",
          color:
            "bg-green-100 text-green-700 border-green-200 dark:bg-green-900/20 dark:text-green-400",
        },
        medium: {
          label: "Média",
          color:
            "bg-yellow-100 text-yellow-700 border-yellow-200 dark:bg-yellow-900/20 dark:text-yellow-400",
        },
        high: {
          label: "Alta",
          color:
            "bg-red-100 text-red-700 border-red-200 dark:bg-red-900/20 dark:text-red-400",
        },
      },
    },
    techNews: {
      categories: [
        { id: "top", name: "Top Stories", icon: TrendingUpIcon },
        { id: "new", name: "Mais Recentes", icon: ClockIcon },
        { id: "best", name: "Melhores", icon: GlobeIcon },
      ],
      fallbackImage:
        "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    youtubePlayer: {
      sampleVideos: [
        {
          id: "dQw4w9WgXcQ",
          title: "Rick Astley - Never Gonna Give You Up (Official Music Video)",
          channelTitle: "Rick Astley",
          thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
          publishedAt: "2009-10-25T06:57:33Z",
        },
        {
          id: "5qap5aO4i9A",
          title: "lofi hip hop radio - beats to relax/study to",
          channelTitle: "Lofi Girl",
          thumbnailUrl: "https://i.ytimg.com/vi/5qap5aO4i9A/hqdefault.jpg",
          publishedAt: "2020-02-22T19:51:37Z",
        },
        {
          id: "jfKfPfyJRdk",
          title: "lofi hip hop radio - beats to sleep/chill to",
          channelTitle: "Lofi Girl",
          thumbnailUrl: "https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg",
          publishedAt: "2021-02-19T01:13:14Z",
        },
        {
          id: "hFDOGYEPZ8E",
          title:
            "Novo Feat e Técnica de Programação que Está Revolucionando o Dev JavaScript",
          channelTitle: "Filipe Deschamps",
          thumbnailUrl: "https://i.ytimg.com/vi/hFDOGYEPZ8E/hqdefault.jpg",
          publishedAt: "2023-08-09T21:12:37Z",
        },
        {
          id: "BrnMl1R4sKA",
          title: "MIT: Introduction to Deep Learning",
          channelTitle: "Alexander Amini",
          thumbnailUrl: "https://i.ytimg.com/vi/BrnMl1R4sKA/hqdefault.jpg",
          publishedAt: "2023-01-09T15:47:22Z",
        },
      ],
    },
  },
};
